font_family   FiraCode Nerd Font
font_size     12


# appearance
background_opacity 0.6
# system
confirm_os_window_close 0

# mapping
map  ctrl+enter      send_text normal,application \x1b[13;5u
map  shift+enter     send_text normal,application \x1b[13;2u
map  ctrl+tab        send_text normal,application \x1b[9;5u
map  ctrl+shift+tab  send_text normal,application \x1b[9;6u
map  ctrl+shift+r    new_tab
# unmap
map ctrl+shift+t no_op

