font_family   FiraCode Nerd Font
font_size     11
bold_font     Bold

# appearance
background_opacity 0.6
tab_bar_style powerline
tab_title_template "{tab.active_wd[tab.active_wd.rfind('/')+1:]}[{tab.active_exe}]" 

# system
confirm_os_window_close 0
enable_audio_bell no
enable_reflow no

# mapping
map  ctrl+enter      send_text normal,application \x1b[13;5u
map  shift+enter     send_text normal,application \x1b[13;2u
map  ctrl+tab        send_text normal,application \x1b[9;5u
map  ctrl+shift+tab  send_text normal,application \x1b[9;6u
map  ctrl+super+t    new_tab
map  ctrl+super+l    next_tab
map  ctrl+super+h    prev_tab
map  ctrl+e          send_text normal,application yazi\n
map  ctrl+super+r   set_tab_title

# unmap
map ctrl+shift+t no_op
map ctrl+shift+r no_op
map ctrl+shift+alt+t no_op
map ctrl+shift+h no_op
