[Preset.Click Interval]
Millisecs=15

[Preset.Options]
Click Type=Double
Use Repeat=true
Repeat Times=10

[Options]
SAFEMODE=false
USE_XEVENT=false

[Preset.More Options]
Use Custom Location=true
Custom X=3072
Custom Y=540
