[manager]
append_keymap = [
  { on = "<C-j>", run = "arrow 5" },
  { on = "<C-k>", run = "arrow -5" },
]
prepend_keymap = [
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = [ "c", "a" ], run = "plugin ouch --args=zip", desc = "Compress with ouch" },
]
