# ----------------------------------------------------- 
# Monitor Setup
# name: "2 monitors"
# ----------------------------------------------------- 

monitor=eDP-1, 3072x1920@120, 0x0, 2
monitor=HDMI-A-1, 1920x1080, 1536x0, 1
