# ----------------------------------------------------- 
# Monitor Setup
# name: "2 monitors"
# ----------------------------------------------------- 
#
monitor=eDP-1, 3072x1920@120, 0x0, 1.6
# monitor=HDMI-A-1, 2560x1440@100, 1920x0, 1
# monitor=HDMI-A-1, 2560x1440@100, 0x0, 1
# monitor=eDP-1, disabled
# monitor=HEADLESS-66, disabled
