# ----------------------------------------------------- 
# Monitor Setup
# name: "2 monitors"
# ----------------------------------------------------- 
#
# monitor=eDP-1, 3072x1920@120, 0x0, 2
# monitor=eDP-1, disabled
monitor=HDMI-A-1, 2560x1440@100, 0x0, 1
# monitor=HDMI-A-1, 2560x1440@100, 1536x0, 1
monitor=HEADLESS-66, 1920x1080@60, 2560x0, 1 
