# Preload Wallpapers
preload = /home/endless_journey/wallpaper/astronaut_jellyfish.jpg

# Set Wallpapers
wallpaper = ,/home/endless_journey/wallpaper/astronaut_jellyfish.jpg

# Disable Splash
splash = false
