[General]
bookmarks=/home/endless_journey
lastDisplay=0
maximizedWindow=true
savedPaths=/home/endless_journey, /home/endless_journey/data, /home/endless_journey/Desktop, /home/endless_journey/Documents, /home/endless_journey/Downloads, /home/endless_journey/go, /home/endless_journey/managed_context, /home/endless_journey/Music, /home/endless_journey/Pictures
windowGeometry=@Rect(13 75 1510 872)
